const C={rounds:5,steps:[.5,1,2,4,8],q:{
"ฮิตไทย":["เพลงไทย","Thai pop","Tilly Birds","Three Man Down","Jeff Satur","NONT TANONT","INK WARUNTORN"],
"T-POP":["T-POP","4EVE","PiXXiE","PROXIE","LYKN","BUS because of you i shine"],
"2000s":["เพลงไทย 2000","Bodyslam","Clash","Big Ass","Potato","Da Endorphine"],
"ลูกทุ่ง":["ลูกทุ่ง","Thai country","มนต์แคน แก่นคูน","ลำไย ไหทองคำ","ก้อง ห้วยไร่"],
"อินดี้":["Thai indie","Safeplanet","Whal & Dolph","Yew","Dept","Tilly Birds"],
"สุ่มทั้งหมด":["เพลงไทย","Thai pop","T-POP","ลูกทุ่ง","Thai indie","Bodyslam","NONT TANONT"]}};
const $=x=>document.getElementById(x),E={setup:$("setup"),loading:$("loading"),game:$("game"),start:$("start"),modes:$("modes"),lt:$("loadingText"),ml:$("modeLabel"),sec:$("seconds"),sec2:$("sec2"),bar:$("bar"),play:$("play"),as:$("audioState"),ans:$("answer"),sugs:$("suggestions"),submit:$("submit"),skip:$("skip"),score:$("score"),round:$("round"),remain:$("remain"),msg:$("msg"),result:$("result"),okIcon:$("okIcon"),okText:$("okText"),art:$("art"),title:$("title"),artist:$("artist"),gain:$("gain"),apple:$("apple"),next:$("next"),finish:$("finish"),final:$("final"),share:$("share"),again:$("again"),copy:$("copy"),home:$("home"),mute:$("mute")};
let mode="ฮิตไทย",pool=[],list=[],r=0,step=0,score=0,audio=null,timer=null,muted=false,selected=null,searchTimer=null;

function jsonp(term,limit=60){return new Promise((res,rej)=>{let cb="__prw"+Date.now()+Math.random().toString(36).slice(2),s=document.createElement("script"),t=setTimeout(()=>done(new Error("timeout")),10000);function done(e,d){clearTimeout(t);delete window[cb];s.remove();e?rej(e):res(d)}window[cb]=d=>done(null,d);let p=new URLSearchParams({term,country:"TH",media:"music",entity:"song",limit:String(limit),callback:cb});s.src="https://itunes.apple.com/search?"+p;s.onerror=()=>done(new Error("network"));document.body.appendChild(s)})}
function clean(a){let m=new Map;(a||[]).forEach(x=>{if(x.previewUrl&&x.trackName&&x.artistName&&!m.has(x.trackId))m.set(x.trackId,{id:x.trackId,title:x.trackName,artist:x.artistName,preview:x.previewUrl,art:(x.artworkUrl100||"").replace("100x100bb","500x500bb"),url:x.trackViewUrl||""})});return[...m.values()]}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
async function build(){let all=[];for(let i=0;i<C.q[mode].length;i++){E.lt.textContent=`กำลังค้นเพลง ${i+1}/${C.q[mode].length}`;try{let d=await jsonp(C.q[mode][i],80);all.push(...clean(d.results))}catch{}}pool=[...new Map(all.map(x=>[x.id,x])).values()];if(pool.length<5)throw Error()}
async function start(){E.setup.classList.add("hidden");E.loading.classList.remove("hidden");E.game.classList.add("hidden");try{await build();list=shuffle(pool).slice(0,5);r=0;step=0;score=0;E.score.textContent=0;E.ml.textContent=mode;E.loading.classList.add("hidden");E.game.classList.remove("hidden");load()}catch{E.loading.classList.add("hidden");E.setup.classList.remove("hidden");alert("โหลดเพลงไม่ได้ ลองเช็กอินเทอร์เน็ตแล้วกดใหม่")}}
function cur(){return list[r]}function stop(){clearTimeout(timer);if(audio){audio.pause();audio.currentTime=0}E.play.textContent="▶"}
function load(){stop();step=0;selected=null;E.ans.value="";E.msg.textContent="";E.sugs.style.display="none";E.round.textContent=r+1;audio=new Audio(cur().preview);audio.muted=muted;draw()}
function draw(){E.sec.textContent=C.steps[step];E.sec2.textContent=C.steps[step];E.bar.style.width=((step+1)*20)+"%";document.querySelectorAll(".levels span").forEach((x,i)=>x.classList.toggle("active",i===step));E.remain.textContent=step===4?"รอบสุดท้าย":`เหลืออีก ${4-step} ระดับ`}
async function play(){stop();try{audio.currentTime=0;E.play.textContent="❚❚";E.as.textContent=`🎵 กำลังเล่น ${C.steps[step]} วินาที…`;await audio.play();timer=setTimeout(()=>{audio.pause();E.play.textContent="▶";E.as.textContent="หยุดแล้ว — ทายเลย!"},C.steps[step]*1000)}catch{E.as.textContent="ลองกด Play อีกครั้ง"}}
const norm=s=>(s||"").toLowerCase().normalize("NFKC").replace(/[()[\]{}"'’“”.,!?\-–—:;/\\]/g," ").replace(/\s+/g," ").trim();
function correct(){let q=norm(E.ans.value),s=cur();return selected&&+selected.id===+s.id||q===norm(s.title)||(q.length>=5&&norm(s.title).includes(q))}
function submit(){if(!E.ans.value.trim()){E.msg.textContent="พิมพ์ชื่อเพลงก่อนนะ";return}show(correct())}
function skip(){if(step<4){step++;draw();E.msg.textContent=`ปลดล็อก ${C.steps[step]} วินาทีแล้ว`}else show(false)}
function show(ok){stop();let pts=ok?Math.max(200,1000-step*180):0;if(ok)score+=pts;E.score.textContent=score;E.okIcon.textContent=ok?"✓":"✕";E.okText.textContent=ok?"ถูกต้อง!":"เฉลย";E.okText.style.color=ok?"#72f0a2":"#ff8181";E.gain.textContent=ok?`+${pts} คะแนน`:"";let s=cur();E.art.src=s.art;E.title.textContent=s.title;E.artist.textContent=s.artist;E.apple.href=s.url||"#";E.result.classList.remove("hidden")}
function next(){E.result.classList.add("hidden");r++;r>=5?finish():load()}
function finish(){stop();E.game.classList.add("hidden");E.final.textContent=score;let txt=`เพลงไรวะ 🎧\n${mode}\n${score} คะแนน / 5 เพลง\n0.5 วิ รู้มั้ยเพลงอะไร?`;E.share.textContent=txt;E.finish.classList.remove("hidden")}
function home(){stop();E.result.classList.add("hidden");E.finish.classList.add("hidden");E.game.classList.add("hidden");E.loading.classList.add("hidden");E.setup.classList.remove("hidden")}
async function search(q){if(q.trim().length<2){E.sugs.style.display="none";return}try{let d=await jsonp(q,10);render(clean(d.results))}catch{render(pool.filter(x=>norm(x.title).includes(norm(q))||norm(x.artist).includes(norm(q))).slice(0,8))}}
function render(a){E.sugs.innerHTML="";a.slice(0,8).forEach(s=>{let b=document.createElement("button");b.type="button";b.className="sug";let im=document.createElement("img");im.src=s.art;let sp=document.createElement("span"),x=document.createElement("b"),y=document.createElement("small");x.textContent=s.title;y.textContent=s.artist;sp.append(x,y);b.append(im,sp);b.onclick=()=>{selected=s;E.ans.value=s.title;E.sugs.style.display="none"};E.sugs.appendChild(b)});E.sugs.style.display=a.length?"block":"none"}
E.modes.onclick=e=>{let b=e.target.closest(".mode");if(!b)return;document.querySelectorAll(".mode").forEach(x=>x.classList.remove("active"));b.classList.add("active");mode=b.dataset.mode};
E.start.onclick=start;E.play.onclick=play;E.submit.onclick=submit;E.skip.onclick=skip;E.next.onclick=next;E.again.onclick=()=>{E.finish.classList.add("hidden");start()};E.home.onclick=home;E.mute.onclick=()=>{muted=!muted;if(audio)audio.muted=muted;E.mute.textContent=muted?"🔇":"🔊"};
E.ans.oninput=()=>{selected=null;clearTimeout(searchTimer);searchTimer=setTimeout(()=>search(E.ans.value),350)};E.ans.onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();submit()}};
E.copy.onclick=async()=>{try{await navigator.clipboard.writeText(E.share.textContent);E.copy.textContent="คัดลอกแล้ว ✓"}catch{E.copy.textContent="กดค้างที่ผลเพื่อคัดลอก"}};
